import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"
import eslintConfigPrettier from "eslint-config-prettier/flat"

const generatedStyleIgnores = [
  // Generated shadcn primitives. Leave them as the CLI produced them.
  "components/ui/**",
  // Regenerated by `bun run db:types`.
  "lib/supabase/database.types.ts",
]

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Design handoff reference files, not app code.
    "design_handoff_iyafyl_home/**",
  ]),
  // Disables ESLint stylistic rules that conflict with Prettier.
  // `curly` is one of those special rules, so it is re-enabled below.
  eslintConfigPrettier,
  {
    files: ["**/*.{js,mjs,cjs,ts,tsx}"],
    ignores: generatedStyleIgnores,
    rules: {
      // "all" is the curly option that does not conflict with Prettier.
      curly: ["error", "all"],
      // typescript-eslint/eslint-recommended (via eslint-config-next) already
      // enables this for TypeScript, including generated files. Repeated here
      // so plain JS is covered too.
      "prefer-const": "error",
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    ignores: generatedStyleIgnores,
    rules: {
      "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
    },
  },
])

export default eslintConfig
